### PR TITLE
Add getSentenceVector to supported commands

### PR DESCRIPTION
**Pull request by benman1**
- Update fb fastText cpp repo to latest. This includes the getSentenceVector.
- Include the getSentenceVector method in java interface.

### CODE REVIEW

**Comment by lidalei** [comment]
Thx a lot for your pull request. Adding `getSentenceVector` will make JFastText more useful.

I have updated the fastText module. Could you use my repo lidalei/fastText?

**Comment by benman1** [comment]
Nice to hear you like it. Sure. I'll change it early next week (on holiday
now).

**Comment by benman1** [comment]
Hi Dalei
 Thanks for getting back to me. I've made the change. Sorry, it took a bit longer than expected. Thanks for waiting.

**Comment by lidalei** [comment]
Thx. But could you really use that repo to resolve merge conflict?

**Comment by benman1** [comment]
I am happy to resolve conflicts if it helps. We are talking about
jfasttext, right? I will try to get it done tomorrow.

**Comment by lidalei** [comment]
Yes. I think you don't have to do any change about fastText. A quick solution could be to merge master branch of JFastText to your branch and push your changes about JFastText.

**Comment by benman1** [comment]
Great, thanks. I'll do that.

**Comment by benman1** [comment]
I struggled for a while resolving the conflicts. In the end, I redid my changes on a clean, new repo. Please close this one, and accept the other pull request.

**Pull request closed without merging**
